/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_zzyun_wsocks_UdpUtil */

#ifndef _Included_co_zzyun_wsocks_UdpUtil
#define _Included_co_zzyun_wsocks_UdpUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_zzyun_wsocks_UdpUtil
 * Method:    initRaw
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_co_zzyun_wsocks_UdpUtil_initRaw
  (JNIEnv *, jclass, jstring, jint, jstring, jint);

/*
 * Class:     co_zzyun_wsocks_UdpUtil
 * Method:    sendUdp
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_co_zzyun_wsocks_UdpUtil_sendUdp
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
